param(
    [string]$Action = "check",
    [string]$Filter = "",
    [string]$Config = "Release",
    [string]$BuildDir = "build"
)

$ErrorActionPreference = "Stop"
$Root = Split-Path -Parent $PSScriptRoot
$Build = Join-Path $Root $BuildDir

function Red   { Write-Host "$($PSStyle.Foreground.Red)$($args[0])$($PSStyle.Reset)" }
function Green { Write-Host "$($PSStyle.Foreground.Green)$($args[0])$($PSStyle.Reset)" }
function Cyan  { Write-Host "$($PSStyle.Foreground.Cyan)$($args[0])$($PSStyle.Reset)" }
function Gray  { Write-Host "$($PSStyle.Foreground.BrightBlack)$($args[0])$($PSStyle.Reset)" }

function Step($Name) { Cyan ">> $Name" }

function Exec($Name, [scriptblock]$Block) {
    Gray "   $Name ..."
    & $Block
    if ($LASTEXITCODE -ne 0) {
        Red "[FAIL] $Name (exit=$LASTEXITCODE)"
        exit $LASTEXITCODE
    }
    Green "[PASS] $Name"
}

function Ensure-Build-Dir {
    if (-not (Test-Path $Build)) {
        Step "Configuring CMake (first time)..."
        cmake -B $Build
        if ($LASTEXITCODE -ne 0) { Red "[FAIL] cmake configure"; exit 1 }
    }
}

function Ensure-Ninja {
    # Verify the build system is usable — detect stale state
    if (-not (Test-Path (Join-Path $Build "build.ninja"))) {
        Step "Reconfiguring (build.ninja missing)..."
        cmake -B $Build
        if ($LASTEXITCODE -ne 0) { Red "[FAIL] cmake reconfigure"; exit 1 }
    }
}

function Invoke-Build($Targets, $Label) {
    Ensure-Build-Dir
    Ensure-Ninja
    Step "Building $Label..."
    foreach ($t in $Targets) {
        Exec "cmake --build $Build --target $t --config $Config" {
            cmake --build $Build --target $t --config $Config 2>&1 | Out-Null
            if ($LASTEXITCODE -ne 0) {
                # Show build output on failure
                cmake --build $Build --target $t --config $Config 2>&1 | Select-String -Pattern "error|fatal|FAILED" | ForEach-Object { Write-Host "   $_" }
            }
        }
    }
}

function Invoke-Ctest($Label, $CtestArgs) {
    Step "Running $Label..."
    Exec "ctest $($CtestArgs -join ' ')" {
        ctest --test-dir $Build -C $Config --output-on-failure @CtestArgs 2>&1 | ForEach-Object {
            if ($_ -match "PASSED|passed") { Green "   $_" }
            elseif ($_ -match "FAILED|failed") { Red "   $_" }
            else { Write-Host "   $_" }
        }
    }
}

# ─── Target lists ───────────────────────────────────────────────
$Libs = @("missile_lib", "missile_cpu")
$CfdAll = @(
    "TestCfdGpu", "TestCfdMesh", "TestCfdEuler",
    "TestCfdDiagnostics", "TestCfdReconstruction", "TestCfdViscous"
)
$CfdGpu   = @("TestCfdGpu")
$CfdCpu   = @("TestCfdMesh", "TestCfdEuler", "TestCfdDiagnostics",
              "TestCfdReconstruction", "TestCfdViscous")
$OtherTest = @("TestAeroViscous", "TestGpuTopology")
# Known broken (pre-existing link/include errors): TestPropulsion, TestAero,
# TestIntegrator, TestLaunch, TestAeroTableGen, TestCompareAtm, TestGuidance, TestAutopilot

# ─── Actions ────────────────────────────────────────────────────
switch -Regex ($Action.ToLower()) {

    "^(check|compile)$" {
        Invoke-Build $Libs "libraries"
        Green "[PASS] check — all libraries compile"
    }

    "^(build|compile-all)$" {
        Invoke-Build $Libs "libraries"
        Invoke-Build ($CfdAll + $OtherTest) "test executables"
        Green "[PASS] build — all targets compile"
    }

    "^test$" {
        Invoke-Build ($Libs + $CfdAll + $OtherTest) "libraries + tests"
        Invoke-Ctest "all working tests" @()
    }

    "^test (cfd-gpu|gpu)$" {
        Invoke-Build ($Libs + $CfdGpu) "libraries + TestCfdGpu"
        Invoke-Ctest "CFD GPU tests" @("-R", "CfdGpu")
    }

    "^test (cfd-cpu|cpu)$" {
        Invoke-Build ($Libs + $CfdCpu) "libraries + CFD CPU tests"
        Invoke-Ctest "CFD CPU tests" @("-R", "Cfd(Mesh|Euler|Diagnostics|Reconstruction|Viscous)")
    }

    "^test cfd$" {
        Invoke-Build ($Libs + $CfdAll) "libraries + all CFD tests"
        Invoke-Ctest "all CFD tests" @("-R", "Cfd")
    }

    "^full$" {
        Invoke-Build ($Libs + $CfdAll + $OtherTest) "everything"
        Invoke-Ctest "all working tests" @()
        Green "[PASS] full — everything OK"
    }

    "^(install-hooks|hooks)$" {
        Step "Installing pre-commit hook..."
        $HookDir = Join-Path (Join-Path $Root ".git") "hooks"
        if (-not (Test-Path $HookDir)) {
            Red "[FAIL] .git/hooks not found — is this a git repo?"
            exit 1
        }
        $HookPath = Join-Path $HookDir "pre-commit"
        $HookContent = @'
#!/usr/bin/env pwsh
# Auto-generated by scripts/ci.ps1 install-hooks
# Exit codes: 0 = pass, non-zero = block commit

$Root = Split-Path -Parent $PSScriptRoot
$Root = Split-Path -Parent $Root  # .git/hooks -> .git -> repo root

$failed = $false

# 1. Check for trailing whitespace in staged files
$staged = & git diff --cached --name-only --diff-filter=ACM
foreach ($f in $staged) {
    $path = Join-Path $Root $f
    if (-not (Test-Path $path)) { continue }
    $ext = [System.IO.Path]::GetExtension($f)
    if ($ext -notin '.cpp','.hpp','.cu','.h','.cuh','.py','.ps1','.cmake') { continue }
    $lines = Get-Content $path
    for ($i = 0; $i -lt $lines.Count; $i++) {
        if ($lines[$i] -match '[ \t]+$') {
            Write-Host "[pre-commit] trailing whitespace in $f line $($i+1)"
            $failed = $true
        }
    }
}

# 2. Quick compilation check
Write-Host "[pre-commit] compiling libraries ..."
$result = & cmake --build (Join-Path $Root "build") --target missile_lib --config Release 2>&1
if ($LASTEXITCODE -ne 0) {
    Write-Host "[pre-commit] FAIL: library compilation error"
    $failed = $true
}

if ($failed) { exit 1 }
Write-Host "[pre-commit] OK"
'@
        Set-Content -Path $HookPath -Value $HookContent -Encoding UTF8
        Green "[PASS] pre-commit hook written to $HookPath"
    }

    default {
        Red "[FAIL] Unknown action '$Action'"
        Write-Host ""
        Write-Host "Usage: .\scripts\ci.ps1 <action> [filter]"
        Write-Host ""
        Write-Host "  check            Quick compile check (libraries only)"
        Write-Host "  build            Full build (libraries + all known-good tests)"
        Write-Host "  test             Build + run all working tests"
        Write-Host "  test cfd-gpu     Build + run CFD GPU tests only"
        Write-Host "  test cfd-cpu     Build + run CFD CPU tests only"
        Write-Host "  test cfd         Build + run all CFD tests"
        Write-Host "  full             Build + all tests (run before commit)"
        Write-Host "  install-hooks    Install pre-commit git hook"
        exit 1
    }
}
